cult-of-coders/grapher

CHANGELOG.md, lib/documentor/index.js, lib/exposure/exposure.config.schema.js, lib/exposure/exposure.js, lib/exposure/lib/intersectDeep.js, lib/exposure/testing/bootstrap/demo.js, lib/exposure/testing/bootstrap/expose.js, lib/exposure/testing/bootstrap/fixtures.js, lib/exposure/testing/bootstrap/intersect.js, lib/exposure/testing/client.js, lib/exposure/testing/server.js, lib/exposure/testing/units/units.js, lib/namedQuery/expose/extension.js, lib/namedQuery/namedQuery.base.js, lib/query/hypernova/hypernova.js, lib/query/hypernova/storeHypernovaResults.js, lib/query/lib/recursiveCompose.js, lib/query/nodes/collectionNode.js, lib/query/query.base.js, package.js
=> [RFC] Added exposure to body #41

lib/exposure/lib/cleanBody.js, lib/links/linker.js, lib/links/tests/main.js, lib/namedQuery/namedQuery.client.js, lib/query/hypernova/buildAggregatePipeline.js, lib/query/nodes/collectionNode.js, lib/query/query.client.js, lib/query/testing/client.test.js, lib/query/testing/lib/waitForHandleToBeReady.js, lib/query/testing/reducers.client.test.js, lib/query/testing/server.test.js, package.js
Bug fixes and consistency fixes.
=> [RFC] Feature/1.2.6

lib/exposure/exposure.js, lib/query/lib/deepClone.js, package.js
=> [RFC] Feature/1.2.7_2

README.md
Phantom seems to be behaving itself now.
=> Remove phantomjs note

lib/query/lib/createGraph.js, lib/query/lib/prepareForDelivery.js, lib/query/testing/server.test.js
I've added support for limit, skip and sort. For sort I'm using Minimongo.Sorter.
I also renamed $postfilter to $postfilters, but kept $postfilter as an alias.
=> $postOptions

lib/links/linkTypes/base.js, lib/query/lib/createGraph.js
Fixes https://github.com/cult-of-coders/grapher/issues/134
=> Default workaround patch

README.md, docs/api.md, docs/named_queries.md, docs/structure_and_patterns.md, lib/links/config.schema.js, lib/namedQuery/expose/extension.js, lib/namedQuery/expose/schema.js, lib/namedQuery/namedQuery.client.js, lib/namedQuery/namedQuery.server.js, lib/namedQuery/testing/server.test.js, lib/query/hypernova/hypernova.js, lib/query/lib/prepareForProcess.js, lib/query/nodes/reducerNode.js, lib/query/testing/bootstrap/authors/links.js, lib/query/testing/link-cache/server.test.js, lib/query/testing/reducers.server.test.js
=> [RFC] Release/1.3.1

docs/global_exposure.md
"ofcourse" should be "of course"
=> Minor grammatical updates.

.travis.yml, lib/exposure/exposure.js, lib/namedQuery/expose/extension.js, lib/namedQuery/testing/client.test.js, lib/query/counts/genEndpoint.server.js, lib/query/counts/testing/bootstrap/namedQuery.test.js, lib/query/counts/testing/client.test.js, lib/query/counts/testing/server.test.js, lib/query/testing/bootstrap/authors/links.js, lib/query/testing/reducers.client.test.js, lib/query/testing/server.test.js, package.js
=> [RFC] Release/1.3.3

README.md
Here's a link to the Meteor Night slide making a case for Grapher and other amazing tools developed by Theodor Diaconu.
=> Added Meteor Night Talk Slide

.gitignore, MIGRATION.md, lib/aggregate.js, lib/query/hypernova/assembleAggregateResults.js, lib/query/hypernova/storeHypernovaResults.js, lib/query/testing/reducers.server.test.js, package.js
- Reducers with one links become one
- Support for Meteor 1.7
=> [RFC] Release/1.3.6

lib/query/hypernova/assembler.js, lib/query/testing/link-cache/server.test.js
We change the strategy a bit and we notice increases of up to 8 times. In procesing the full grapher query. This is absolutely jaw-breaking.
=> Performance fixes for assembler

lib/query/lib/recursiveCompose.js
Should fix bug from this [comment](https://github.com/cult-of-coders/grapher/pull/296#issuecomment-432956096)
=> Pass config to the nested publications in recursiveCompose

docs/named_queries.md
"ofcourse" should be "of course"
=> Minor grammatical corrections.

lib/query/reducers/lib/embedReducerWithLink.js
=> Fix non-denormalized data in deep reducers error

lib/query/hypernova/buildAggregatePipeline.js, lib/query/testing/server.test.js
dates were removed from the query pipeline
fixes issue #384
=> fix buildAggregatePipeline : dates filtering didn't work on linked collections

lib/query/nodes/collectionNode.js
=> Omit $expr operator from projected field names

lib/query/query.server.js
Inspired by meteor's findOne
Closes #446
=> Improve fetchOne to only return 1 result

lib/exposure/exposure.config.schema.js, lib/exposure/exposure.js
=> Fix global exposure function body usage

.npm/package/npm-shrinkwrap.json, lib/links/lib/createSearchFilters.js, lib/namedQuery/testing/client.test.js, lib/query/lib/prepareForDelivery.js, lib/query/testing/client.test.js, package.js
- updated denormalize package
- note that sift was quite a few versions back
- all tests are passing
=> updated package.js, updated packages, fixed broken tests

docs/index.md
I am a huge fan of grapher. Was reading the docs and noticed a little typo and wanted to contribute :)
=> Quick little wording edit in docs

lib/query/lib/prepareForDelivery.js, lib/query/testing/server.test.js
Reverts cult-of-coders/grapher#405
=> Revert "Fix for storeOneResults when handling already processed results"

lib/query/hypernova/hypernova.js
It is called in storeHypernovaResults, right after.
=> Remove unnecessary applyProps call
