cult-of-coders/grapher

- lib/query/lib/deepClone.js
Currently `col.createQuery({ $filters: { name: { $regex: ...  } } }).fetch()` doesn't work
> Fix issue with $regex operator

- lib/query/lib/deepClone.js
I found a bug in grapher which caused Date queries to fail.
The deepClone in grapher does transform a $filter like this:
```js
{
$filters: {
dateField: { $gte: new Date() }
}
}
```
to an empty object:
```js
{
$filters: {
dateField: {}
}
}
```
My solution is to add a `_.isDate` check to the existing checks in the deepClone function. This works for JS Dates but there might be some more problematic types.
Maybe a better solution would be to replace the custom deepClone with the lodash deepClone?
> Fixed deepClone of Date objects

- lib/namedQuery/namedQuery.client.js
- lib/query/query.client.js
- lib/query/testing/client.test.js
This PR adds new promise support also for getCount methods for both query and namedQuery on the client.
I was wondering why promise support has not been implemented using the same methods used for traditional callback approach. Is it to have these Exceptions complaining about a missing callback function?
e.g `getCount(callback)` could be easily implemented as
```js
async getCount(callback) {
return await callWithPromise(this.name + '.count', prepareForProcess(this.body, this.params), callback);
}
```
It would still be absolutely fine to call it by using the callback and ignoring the returned promise.
> Adds promise (sync) variants of getCount

- lib/links/extension.js
I'd like to have a method that returns all the links attached to a collection.
See issue #96
> Add a method to get all attached links

- lib/query/nodes/collectionNode.js
```
Meteor.users.createQuery({
$filters:{'profile.online':true},
username:1,
profile:1
}
```
If you try to create a query like this, both 'profile.online' and 'profile' get added to options.fields, causing the error 
> "MinimongoError: both profile.online and profile found in fields option, using both of them may trigger unexpected behavior."
This adds a check to not add fields if options.fields already contains their parent.
> fix issue with adding fields from $filters

- lib/namedQuery/expose/extension.js
Currently any param validation errors raised in `_validateParams` are not logged anywhere, which can make debugging difficult. This PR causes any errors to be output via `console.error` when not running in production mode.
Additionally, the count method of each named query will run the firewall method before returning any data.
> Named query validation/firewall changes

- docs/denormalization.md
I could be wrong on this, but I got lost trying to follow this.  Shouldn't the filter review to `reviewedBooksCache` and not `bookReviewsCache`. My apologies if not, guess I'm not understanding it.
> Possible mistake in naming of reviewedBooksCache

- lib/query/hypernova/buildAggregatePipeline.js
- lib/query/hypernova/lib/snapBackDottedFields.js
- lib/query/lib/recursiveFetch.js
- lib/query/reducers/lib/cleanReducerLeftovers.js
- lib/query/reducers/lib/embedReducerWithLink.js
- lib/query/testing/bootstrap/authors/links.js
- lib/query/testing/bootstrap/fixtures.js
- lib/query/testing/bootstrap/posts/links.js
- lib/query/testing/link-cache/fixtures.js
- lib/query/testing/link-cache/server.test.js
- lib/query/testing/reducers.client.test.js
- lib/query/testing/reducers.server.test.js
- lib/query/testing/server.test.js
1. Denormalized fields in embedReducerWithLink() were not handled properly causing errors
2. Nested fields in embedReducerWithLink() were not handled properly
Both these issues cause problems while using reducers that use the same link, e.g. 
```
commentsReducer1: {
body: {
posts: {
authorCached: {
name: 1,
},
}
},
....
},
commentsReducer2: {
body: {
posts: {
authorCached: {
name: 1,
},
metadata: {
keywords: 1
},
}
},
}
```
Both reducers use link posts and inside it denormalized authorCached link which failed in embedReducerWithLink() while handling a linker object.
Using metadata in commentsReducer2  failed when collectionNode.body[key] was not set in embedReducerWithLink().
3. Handling cases when cleaning nested fields inside reducers caused an error if the field did not exist.
4. …
> Reducers and deeply nested fields inside links fixes

- lib/namedQuery/namedQuery.client.js
- lib/namedQuery/testing/client.test.js
- lib/query/testing/link-cache/fixtures.js
- lib/query/testing/link-cache/server.test.js
Fixed client side named query sync functions *fetchSync()* and *getCountSync()*. Instead of query body, **params** must passed to the Meteor.call().
Fixes #260
> Sync fetching for named queries fix

- MIGRATION.md
- docs/query_options.md
Been using grapher for a while and finally migrated to 1.3 -- I was stuck migrating for a while and found the migration docs a bit vague. Added an example just in case people were confused like I was. Thanks for the consistent high quality maintenance of this package!
> Clarification in migration docs & small spelling fix

- lib/query/lib/prepareForDelivery.js
- lib/query/testing/server.test.js
This should fix #315. The problem occurred when there was no data on the other side of inversedBy link which referenced unique link.
@theodorDiaconu 
Another issue I noticed while writing tests was that the link storage was not cleared properly so I think I fixed that, too.
And one question. I noticed  that `removeLinkStorages` does not try to delete `$metadata` even when `shouldCleanStorage` flag is true. Is this intentional, ie if we remove $metadata would it break some other things?
> Fix #315 - inversedBy links to unique links

- lib/query/lib/recursiveFetch.js
- lib/query/testing/bootstrap/index.js
- lib/query/testing/bootstrap/posts/links.js
- lib/query/testing/bootstrap/users/links.js
- lib/query/testing/client.test.js
Fixing bug I introduced in earlier PR-s related to reactive queries and handling normalized fields client-side. 
There might be duplicates in `collectionNode.results` in `recursiveFetch` and it is not enough to use only unique subset of these documents, all objects must be added to the results so that `snapBackCaches` can make changes on each instances.
> Recursive fetch update

- lib/query/nodes/collectionNode.js
We've had a hard time tracking down why an invalid query was throwing an error, because we couldn't figure out which field was a collection and had a missing body.
This simply displays the linkName in the error message to make it easier to fix the issue.
> Add linkName in error message

- lib/query/lib/recursiveCompose.js
I managed to misread the docs and made a serious bug while patching the `cursor.observe` function.
This only happens to reactively fetched scoped queries.
The `originalObserve` value is not returned from the new function and hence the publishComposite cannot stop the handle when subscription is over.
> Fix observer leaks for scoped queries

- lib/namedQuery/expose/extension.js
We rename strange named variable `newParams` to `params` in `getSession()` function.
This fixes #345 a non-working firewall for count subscriptions.
> Fix: #345 calling firewall without params in `getSession()`

- lib/namedQuery/expose/extension.js
- lib/namedQuery/namedQuery.server.js
A simple omission, but an `embody` function does not get the `params` when a query is reactive, because `this.params` is never set inside `_initPublication`.
Another option would be to use `setParams` at the start of a publication, not sure what you prefer.
> Publications should have params in embody

- package.js
Version 0.4.0 was causing errors with the latest Meteor build and needed to be republished. These discussions describe the problem:
https://github.com/peerlibrary/meteor-subscription-scope/pull/3
https://github.com/meteor/meteor/pull/10522#issuecomment-533249023
This PR just bumps peerlibrary:subscription-scope from 0.4.0 to 0.5.0 which fixes the issue.
> Bump peerlibrary:subscription-scope from 0.4.0 to 0.5.0

- lib/query/hypernova/assembler.js
- lib/query/testing/server.test.js
Having undefined values in parent.results is causing all sorts of bugs in prepareForDelivery.js due to accessing fields of "undefined" in node.results.
> Filter out undefined values from filterAssembledData()

- lib/links/linker.js
- lib/links/tests/main.js
with the empty array.
Many unique relationships are valid (i.e. posts and comments) but currently indexing them results in ` BulkWriteError: E11000 duplicate key error collection: meteor.test_post index: commentUniqueIds_1 dup key: { : null }`.
This PR addresses this by using `partialFilterExpression` if `!this.isSingle()` so that empty arrays do not cause duplicate key errors.
> For Many links support partial filter index to allow multiple documents

- lib/links/linkTypes/linkMany.js
- lib/links/tests/client.test.js
- package.js
There is a limitation in minimongo's handling of $pull, so this simple new test in which a comment is removed via linkMany from its post causes the following error on the client:
```
Error: Unrecognized logical operator: $in
at packages/minimongo.js?hash=bb17400235469027310b81f0d525d28875f12863:642:15
at Array.map (<anonymous>)
at compileDocumentSelector (packages/minimongo.js?hash=bb17400235469027310b81f0d525d28875f12863:635:48)
at Matcher._compileSelector (packages/minimongo.js?hash=bb17400235469027310b81f0d525d28875f12863:4013:12)
at new Matcher (packages/minimongo.js?hash=bb17400235469027310b81f0d525d28875f12863:3944:29)
at $pull (packages/minimongo.js?hash=bb17400235469027310b81f0d525d28875f12863:3653:23)
at packages/minimongo.js?hash=bb17400235469027310b81f0d525d28875f12863:3075:9 …
```
> LinkMany $pull fix

- lib/query/lib/recursiveFetch.js
Currently fetchOptions are not passed recursively to child
collection nodes.
This is causing collisions across scoped queries on results
of child collection nodes.
> Fix recursiveFetch to respect fetchOptions.scope on recursion

- package.js
This updates packages and dependency resolutions to be compatible with Meteor 2.3, with the exception of this chain:
`accounts-base@1.1.1 <- lai:collection-extensions 0.2.1_1 <- dburles:mongo-collection-instances 0.3.5 <- cultofcoders:grapher 1.3.19`
> Dependencies & version resolution for Meteor 2.3

- lib/graphql/lib/astToBody.js
> fix: add support for input types to `getArgs`

- lib/links/linkTypes/linkMany.js
The wording of the error messages being thrown is for single links, not many links.
> Corrects error messages thrown by linkMany

- lib/query/lib/prepareForDelivery.js
This result value can not only be undefined, but also null sometimes. This simple fix prevents grapher from having really deep crashes.
Similar issue as https://github.com/cult-of-coders/grapher/issues/315.
Here's a sample stack trace:
```sh
I20191202-14:01:20.224(1)? Exception while invoking method 'myMethod' TypeError: Cannot read property
'contacts' of null
I20191202-14:01:20.224(1)?     at _.each.result (packages/cultofcoders:grapher/lib/query/lib/prepareForDel
ivery.js:157:51)
I20191202-14:01:20.224(1)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20191202-14:01:20.224(1)?     at node.collectionNodes.forEach.collectionNode (packages/cultofcoders:graph
er/lib/query/lib/prepareForDelivery.js:150:11)
I20191202-14:01:20.224(1)?     at Array.forEach (<anonymous>) …
```
> Always check object exists before accessing its properties

- lib/query/lib/prepareForDelivery.js
- lib/query/testing/server.test.js
Adds check in `storeOneResults()` function to handle already processed collection results.
It can happen that instead of an array, an object is passed to the function.
> Fix for storeOneResults when handling already processed results

- lib/exposure/exposure.js
- lib/namedQuery/expose/extension.js
- lib/query/lib/recursiveCompose.js
This PR lets the `blocking: true` parameter in your config pass through to publications. From the comment [here](Meteor-Community-Packages/meteor-publish-composite#48), it seems like it doesn't cause any problems.
As a general rule in my team, we think you should never block any code with Meteor anyways, as you should cascade any subsequent calls on the client side. Assuming code will execute in the right order is a bad idea, always use callbacks, chained promises, or simply synchronous code.
Testing this in production now, will report back with some results :)
> Allow unblocking recursive publications

- .gitignore
- README.md
- docs/linking_collections.md
- lib/links/config.schema.js
- lib/links/lib/createSearchFilters.js
- lib/links/linkTypes/base.js
- lib/links/linkTypes/lib/smartArguments.js
- lib/links/linkTypes/linkMany.js
- lib/links/linker.js
- lib/links/tests/main.js
- lib/namedQuery/testing/bootstrap/queries/index.js
- lib/namedQuery/testing/bootstrap/queries/productAttributesList.js
- lib/namedQuery/testing/bootstrap/queries/productsList.js
- lib/namedQuery/testing/client.test.js
- lib/namedQuery/testing/server.test.js
- lib/query/hypernova/aggregateSearchFilters.js
- lib/query/hypernova/assembler.js
- lib/query/hypernova/processVirtualNode.js
- lib/query/hypernova/storeHypernovaResults.js
- lib/query/nodes/collectionNode.js
- lib/query/testing/bootstrap/fixtures.js
- lib/query/testing/bootstrap/index.js
- lib/query/testing/bootstrap/products/collection.js
- lib/query/testing/bootstrap/products/links.js
- lib/query/testing/client.test.js
Implementation of a feature as discussed in #396
> Links with `foreignIdentityField`
